version: "3.8"

networks:
  traefik:
    external: true
  socketproxy:
    external: true

volumes:
  traefik-storage: {}

services:
  # ========================================================================= #
  #                                 REVERSE PROXY
  # ========================================================================= #

  # # # TESTCONTAINER
  # whoami:
  #   image: traefik/whoami
  #   container_name: whoami
  #   networks:
  #     - traefik
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.docker.network=traefik"
  #     - "traefik.http.routers.whoami.rule=Host(`whoami.${DOMAIN}`)"
  #     - "traefik.http.routers.whoami.entrypoints=websecure"
  #     - "traefik.http.routers.whoami.tls.certresolver=letsencrypt"

  traefik:
    container_name: traefik
    image: traefik:v2.6
    restart: unless-stopped
    depends_on:
      - socketproxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - traefik
      - socketproxy
    volumes:
      # REPLACED BY SOCKETPROXY | --providers.docker.endpoint
      # - /var/run/docker.sock:/var/run/docker.sock
      - traefik-storage:/certificates
    environment:
      - TZ=${TZ}
    command:
      # Enable API + dashboard
      - --api.dashboard=true
      - --api.debug=true
      # Set log level (DEBUG, PANIC, FATAL, ERROR, WARN, INFO)
      - --log.level=PANIC
      # Enable metrics
      - --metrics.prometheus=true
      - --ping=true
      # Enable correct usage of timezone for logs
      # - --accesslog.fields.names.StartUTC=drop
      # Docker settings
      # - --providers.docker.swarmmode=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=traefik
      - --providers.docker.endpoint=tcp://socketproxy:2375
      - --providers.providersThrottleDuration=10s
      # Entrypoints http/https + redirection to  https
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --entrypoints.websecure.address=:443
      # LetsEncrypt certificates settings
      - --certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/certificates/acme.json
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      # Enable LetsEncrypt staging server
      # - --certificatesresolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.middlewares=authelia@docker"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.routers.api.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=test:lol123"

  socketproxy:
    container_name: socketproxy
    image: tecnativa/docker-socket-proxy:latest
    restart: unless-stopped
    ports:
      - 2375
    networks:
      - socketproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      CONTAINERS: 1
      SERVICES: 1
      NETWORKS: 1
      TASKS: 1