version: "3.8"

services:
  ddclient:
    container_name: ddclient
    image: linuxserver/ddclient:3.9.1
    restart: unless-stopped
    volumes:
      - ./ddclient.conf:/config/ddclient.conf
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
